name: Maven package and Docker package and verify

on:
  push:
    branches:
      - main

jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
        contents: read
        packages: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Logging into Docker
      run: docker login ghcr.io -u lovedepment -p ${{ github.token }}
    - name: Builds the Docker image
      run: docker build . -t ghcr.io/lovedepment/cubix/1/homework/app:springboot
    - name: Publishing the Docker iamge
      run: docker push ghcr.io/lovedepment/cubix/1/homework/app:springboot

  verify-image:
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v3  
    - name: Docker login
      run: docker login ghcr.io -u lovedepment -p ${{ github.token }}
    - name: Verify Docker image
      run: ./verify-image.sh
